= Frankie

== Meals

Frankie has two meals a day; a cup of kibble and a spoonful of wet food for breakfast and dinner.
Breakfast is whenever you get up, dinner is 5pm -- she'll let you know :)

== Medication

The medication is Gabapentin, low level pain relief for her back.

If you feel like it, one white pill twice a day.
If she's being a shit, then don't worry about it.

I've tried to put the contents in her food but that makes her not eat the food.
I cover the pill in peanut butter and shove it down her throat.

== After dinner treat

Around 7 I Frankie gets one Greenies dental treat.

== Bed time

When we're ready to go to bed we say "Frankie, bed time", then take her out for a wee.
That's our cue for her to go to bed.

She might sleep in the bed with you, but if she's anxious she'll probably sleep on the floor.

== Poo poo pee pee time

Frankie will have a wee any time you take her outside.
She generally tends to poop twice a day, but sometimes she'll save it up for a day.


== Her eye

Frankie's has occasional palsey in the cranial nerve III in her right eye.
This affects her ability to control the dilation of the pupil the direction of the eye.
It's not painful, but it does make her look like she's had a stroke.
It happens about once a year then goes away after a few months.

== Thank you!

Thank you for looking after Frankie. I appreciate it a lot!

Please enjoy the gifts!
